# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtag',
            name='description',
            field=models.TextField(default='loltest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
