# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0002_auto_20170420_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpostattachment',
            name='file',
            field=models.FileField(max_length=102400, upload_to='attachments'),
        ),
    ]
