# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0003_auto_20170424_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantype',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='num_threads',
            field=models.IntegerField(default=0),
        ),
    ]
