# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0004_auto_20170424_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbody',
            name='body',
            field=models.CharField(max_length=57344),
        ),
    ]
