# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0005_auto_20170501_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpost',
            name='thread',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='civforum.Thread'),
            preserve_default=False,
        ),
    ]
