# Generated by Django 2.1 on 2018-08-31 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0008_auto_20170705_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='ban_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='civforum.BanType'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='forecaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_forecaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prediction_judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='rigor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='civforum.Rigor'),
        ),
        migrations.AlterField(
            model_name='tpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tpost',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civforum.Mood'),
        ),
        migrations.AlterField(
            model_name='tpurpose',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='civforum.Purpose'),
        ),
        migrations.AlterField(
            model_name='ttag',
            name='tagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
