# Generated by Django 2.1 on 2018-09-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civforum', '0009_auto_20180831_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='reverse',
            field=models.CharField(default='newthread', max_length=100),
        ),
    ]
